<?php // NOT NEEDED HERE > if ( ! defined('WOODMART_THEME_DIR')) exit('No direct script access allowed');

/**
 * ------------------------------------------------------------------------------------------------
 * WPB CSS parts variables for CSS Generator
 * ------------------------------------------------------------------------------------------------
 */

return apply_filters(
	'woodmart_wpbcss_parts',
	array(
		'base_elements'        => array(
			'id'      => 'base_elements',
			'title'   => 'Basic elements',
			'section' => 'Basic elements',
			'checked' => false,
		),
		'vc_table'             => array(
			'id'      => 'vc_table',
			'title'   => 'Table',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
		),
		'button'               => array(
			'id'      => 'button',
			'title'   => 'Button',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/button.jpg',
		),
		'vc_buttons'           => array(
			'id'      => 'vc_buttons',
			'title'   => 'Button set',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
		),
		'vc_message_box_front' => array(
			'id'      => 'vc_message_box_front',
			'title'   => 'Message box',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/message_box.jpg',
		),
		'vc_hoverbox'          => array(
			'id'      => 'vc_hoverbox',
			'title'   => 'Hoverbox',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/hoverbox.gif',
		),
		'vc_pagination'        => array(
			'id'      => 'vc_pagination',
			'title'   => 'Pageable content container',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/pageable_content_container.gif',
		),
		'vc_charts'            => array(
			'id'      => 'vc_charts',
			'title'   => 'Line and round charts',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/line_round_charts.jpg',
		),
		'vc_icon_element'      => array(
			'id'      => 'vc_icon_element',
			'title'   => 'Icon element',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/icon_element.jpg',
		),
		'vc_progress_bar'      => array(
			'id'      => 'vc_progress_bar',
			'title'   => 'Progress bar',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/progress_bar.jpg',
		),
		'vc_pie'               => array(
			'id'      => 'vc_pie',
			'title'   => 'Pie chart',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/pie_chart.jpg',
		),
		'vc_separator'         => array(
			'id'      => 'vc_separator',
			'title'   => 'Separator',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/separator.jpg',
		),
		'vc_zigzag'            => array(
			'id'      => 'vc_zigzag',
			'title'   => 'Zigzag separator',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/zigzag_separator.jpg',
		),
		'vc_toggle'            => array(
			'id'      => 'vc_toggle',
			'title'   => 'FAQ element',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/faq_element.jpg',
		),
		'vc_custom_heading'    => array(
			'id'      => 'vc_custom_heading',
			'title'   => 'Custom heading',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/custom_heading.jpg',
		),
		'vc_call_to_action3'   => array(
			'id'      => 'vc_call_to_action3',
			'title'   => 'Call to action',
			'section' => 'Basic elements',
			'parent'  => 'base_elements',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/call_to_action.jpg',
		),
		'galleries'            => array(
			'id'      => 'galleries',
			'title'   => 'Galleries',
			'section' => 'Galleries',
			'checked' => false,
		),
		'vc_image_gallery'     => array(
			'id'      => 'vc_image_gallery',
			'title'   => 'Image gallery',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/image_gallery.jpg',
		),
		'vc_grid'              => array(
			'id'      => 'vc_grid',
			'title'   => 'Posts and media grids',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/posts_and_media_grids.jpg',
		),
		'vc_carousel'          => array(
			'id'      => 'vc_carousel',
			'title'   => 'Image carousel',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/image_carousel.gif',
		),
		'vc_single_image'      => array(
			'id'      => 'vc_single_image',
			'title'   => 'Single image',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/single_image.jpg',
		),
		'vc_video_widget'      => array(
			'id'      => 'vc_video_widget',
			'title'   => 'Video widget',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/video_widget.jpg',
		),
		'vc_post_slider'       => array(
			'id'      => 'vc_post_slider',
			'title'   => 'Post slider',
			'section' => 'Galleries',
			'parent'  => 'galleries',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/post_slider.gif',
		),
		'extra'                => array(
			'id'      => 'extra',
			'title'   => 'Extras',
			'section' => 'Extras',
			'checked' => false,
		),
		'vc_social_btns'       => array(
			'id'      => 'vc_social_btns',
			'title'   => 'Social buttons',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/social_buttons.jpg',
		),
		'vc_google_maps'       => array(
			'id'      => 'vc_google_maps',
			'title'   => 'Google Maps',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/google_maps.jpg',
		),
		'css3_animations'      => array(
			'id'      => 'css3_animations',
			'title'   => 'CSS3 animations',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/css_animations.gif',
		),
		'pixel_icons'          => array(
			'id'      => 'pixel_icons',
			'title'   => 'Pixel icons',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/pixel_icons.jpg',
		),
		'vc_widgetised_column' => array(
			'id'      => 'vc_widgetised_column',
			'title'   => 'Widgetised Sidebar',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/widgetised_sidebar.jpg',
		),
		'parallax'             => array(
			'id'      => 'parallax',
			'title'   => 'Parallax video',
			'section' => 'Extras',
			'parent'  => 'extra',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'tooltips-wpb-generator/parallax_video.jpg',
		),
	)
);
